import type {
  Category,
  MenuItem,
  Offer,
  Order,
  RestaurantSettings,
  Testimonial,
} from '@/types';

export const defaultSettings: RestaurantSettings = {
  name: 'Qissa Khawani',
  tagline: "We're an authentic north Indian eatery only trying to compete with your grandma at what we do.",
  phone: '+91 96867 54003',
  whatsappNumber: '919686754003',
  email: 'hello@qissakhawani.com',
  address: 'Indiranagar, Bengaluru',
  city: 'Bengaluru',
  openingTime: '12:00 PM',
  closingTime: '11:00 PM',
  instagram: 'https://instagram.com/qissakhawani',
};

export const defaultCategories: Category[] = [
  { id: 'biryanis', name: 'Biryanis', sortOrder: 1, active: true },
  { id: 'kebabs', name: 'Kebabs', sortOrder: 2, active: true },
  { id: 'kormas', name: 'Kormas & Estew', sortOrder: 3, active: true },
  { id: 'breads', name: 'Breads', sortOrder: 4, active: true },
  { id: 'desserts', name: 'Desserts', sortOrder: 5, active: true },
  { id: 'lassi', name: 'Lassi', sortOrder: 6, active: true },
];

export const defaultMenu: MenuItem[] = [
  {
    id: 'lucknowi-dum-gosht',
    name: 'Lucknowi Dum Gosht Biryani',
    categoryId: 'biryanis',
    description: 'The dish that never lies. Mutton cooked in ghee.',
    image: '/menu/mutton-dum-biryani.png',
    tag: 'Signature',
    available: true,
    variants: [
      { id: '2pcs', label: '2 Pcs', price: 275 },
      { id: '3pcs', label: '3 Pcs', price: 450 },
      { id: '5pcs', label: '5 Pcs', price: 625 },
    ],
  },
  {
    id: 'lucknowi-dum-murgh',
    name: 'Lucknowi Dum Murgh Biryani',
    categoryId: 'biryanis',
    description: 'Fragrant rice. Tender chicken. No shortcuts.',
    image: '/menu/chicken-dum-biryani.png',
    tag: 'House favourite',
    available: true,
    variants: [
      { id: '2pcs', label: '2 Pcs', price: 250 },
      { id: '3pcs', label: '3 Pcs', price: 380 },
      { id: '5pcs', label: '5 Pcs', price: 480 },
    ],
  },
  {
    id: 'kalkatiya-dum-gosht',
    name: 'Kalkatiya Dum Gosht Biryani',
    categoryId: 'biryanis',
    description: 'Mutton, egg, potato and a citrus finish.',
    image: '/menu/lucknow-biryani.png',
    available: true,
    variants: [
      { id: '2pcs', label: '2 Pcs (1 egg, 1 potato)', price: 450 },
      { id: '3pcs', label: '3 Pcs (1 egg, 1 potato)', price: 615 },
      { id: '5pcs', label: '5 Pcs (2 eggs, 2 potatoes)', price: 865 },
    ],
  },
  {
    id: 'shahi-paneer-pulao',
    name: 'Shahi Paneer Pulao',
    categoryId: 'biryanis',
    description: 'Vegetarian. Paneer, jasmine rice and sweet green peas.',
    image: '/menu/lucknow-biryani.png',
    tag: 'Veg',
    available: true,
    variants: [
      { id: 'half', label: 'Half', price: 260 },
      { id: 'full', label: 'Full', price: 545 },
    ],
  },
  {
    id: 'mutton-galouti',
    name: 'Mutton Galouti Kebab',
    categoryId: 'kebabs',
    description: 'Melt-in-mouth. Fire-finished. Cooked to perfection.',
    image: '/menu/galouti-kebab.png',
    tag: 'From the tandoor',
    available: true,
    variants: [
      { id: '4pcs', label: '4 Pcs', price: 275 },
      { id: '8pcs', label: '8 Pcs', price: 550 },
      { id: '12pcs', label: '12 Pcs', price: 775 },
    ],
  },
  {
    id: 'bhuna-gosht-korma',
    name: 'Bhuna Gosht Korma',
    categoryId: 'kormas',
    description: 'Rich mutton gravy. Slow-cooked till it falls for you.',
    image: '/menu/rogan-josh.png',
    available: true,
    variants: [
      { id: 'half', label: 'Half (3 Pcs)', price: 450 },
      { id: 'full', label: 'Full (5 Pcs)', price: 765 },
    ],
  },
  {
    id: 'bhuna-murgh-korma',
    name: 'Bhuna Murgh Korma',
    categoryId: 'kormas',
    description: 'Chicken slow-cooked in a deep, fragrant korma.',
    image: '/menu/butter-chicken.png',
    available: true,
    variants: [
      { id: 'half', label: 'Half (3 Pcs)', price: 325 },
      { id: 'full', label: 'Full (5 Pcs)', price: 620 },
    ],
  },
  {
    id: 'mutton-estew',
    name: 'Mutton Estew',
    categoryId: 'kormas',
    description: 'Anglo-Indian heirloom mutton stew.',
    image: '/menu/dal-makhani.png',
    available: true,
    variants: [
      { id: 'half', label: 'Half (3 Pcs)', price: 450 },
      { id: 'full', label: 'Full (5 Pcs)', price: 765 },
    ],
  },
  {
    id: 'ulte-tawa-paratha',
    name: 'Ulte Tawa Paratha',
    categoryId: 'breads',
    description: 'Crisp, flaky, made for scoops of korma.',
    image: '/menu/aloo-paratha.png',
    available: true,
    variants: [{ id: '1pc', label: '1 Pc', price: 40 }],
  },
  {
    id: 'dei-ka-paratha',
    name: 'Dei Ka Paratha',
    categoryId: 'breads',
    description: 'Soft layered paratha, two to a plate.',
    image: '/menu/garlic-butter-naan.png',
    available: true,
    variants: [{ id: '2pcs', label: '2 Pcs', price: 130 }],
  },
  {
    id: 'galouti-roll',
    name: 'Mutton Galouti Roll',
    categoryId: 'breads',
    description: 'Galouti wrapped in Ulte Ka Paratha.',
    image: '/menu/paneer-kulcha.png',
    available: true,
    variants: [{ id: '1pc', label: '1 Pc', price: 175 }],
  },
  {
    id: 'shahi-tukda',
    name: 'Shahi Tukda',
    categoryId: 'desserts',
    description: 'Royal bread pudding. Warm, sweet, unforgettable.',
    image: '/menu/gulab-jamun.png',
    available: true,
    variants: [{ id: 'plate', label: '1 Plate', price: 175 }],
  },
  {
    id: 'mango-lassi',
    name: 'Mango Lassi',
    categoryId: 'lassi',
    description: 'Thick, chilled, and properly mango.',
    image: '/menu/rice-kheer.png',
    available: true,
    variants: [{ id: 'glass', label: '1 Glass', price: 130 }],
  },
  {
    id: 'kesari-lassi',
    name: 'Kesari Lassi',
    categoryId: 'lassi',
    description: 'Saffron-kissed lassi.',
    image: '/menu/gajar-halwa.png',
    available: true,
    variants: [{ id: 'glass', label: '1 Glass', price: 150 }],
  },
  {
    id: 'safed-lassi',
    name: 'Safed Lassi',
    categoryId: 'lassi',
    description: 'Classic plain lassi. Clean and cool.',
    image: '/menu/rice-kheer.png',
    available: true,
    variants: [{ id: 'glass', label: '1 Glass', price: 110 }],
  },
];

export const defaultOffers: Offer[] = [
  {
    id: 'welcome-indiranagar',
    title: 'Now in Indiranagar',
    description: 'Same Lucknowi kitchen stories — now closer to you on 100 Ft Road.',
    active: true,
  },
  {
    id: 'weekday-biryani',
    title: 'Weekday Biryani Love',
    description: 'Add a lassi free on weekday biryani orders above ₹500. Mention code QISSA500.',
    code: 'QISSA500',
    discountPercent: 0,
    active: true,
  },
];

export const defaultTestimonials: Testimonial[] = [
  {
    id: 't1',
    customerName: 'Ananya R.',
    message: 'The Galouti literally melts. Ordered on WhatsApp before — this site made it so much easier.',
    rating: 5,
    approved: true,
    createdAt: '2026-09-07T10:20:00.000Z',
  },
  {
    id: 't2',
    customerName: 'Rohan M.',
    message: 'Dum Gosht Biryani tastes like home. Confirmations are clear and the kitchen is on time.',
    rating: 5,
    approved: true,
    createdAt: '2026-09-06T18:05:00.000Z',
  },
  {
    id: 't3',
    customerName: 'Priya S.',
    message: 'Finally an ordering flow that doesn’t need 10 Instagram DMs. Shahi Tukda is unreal.',
    rating: 5,
    approved: true,
    createdAt: '2026-09-05T14:40:00.000Z',
  },
  {
    id: 't4',
    customerName: 'Karthik V.',
    message: 'Ordered Bhuna Murgh + Ulte Tawa Paratha for office. Packaging was solid, taste was fire.',
    rating: 5,
    approved: false,
    createdAt: '2026-09-09T05:10:00.000Z',
  },
  {
    id: 't5',
    customerName: 'Meera D.',
    message: 'Kesari Lassi is dangerous. Please never change the recipe.',
    rating: 4,
    approved: false,
    createdAt: '2026-09-08T20:30:00.000Z',
  },
];

export const defaultOrders: Order[] = [
  {
    id: 'QK-DEMO-1001',
    customerName: 'Ananya R.',
    phone: '9876543210',
    address: '12th Main, Indiranagar',
    orderMode: 'Delivery',
    items: [
      {
        menuItemId: 'lucknowi-dum-murgh',
        name: 'Lucknowi Dum Murgh Biryani',
        variantId: '3pcs',
        variantLabel: '3 Pcs',
        unitPrice: 380,
        quantity: 1,
      },
      {
        menuItemId: 'mango-lassi',
        name: 'Mango Lassi',
        variantId: 'glass',
        variantLabel: '1 Glass',
        unitPrice: 130,
        quantity: 2,
      },
    ],
    totalPrice: 640,
    totalItems: 3,
    note: 'Less spice please',
    createdAt: '2026-09-09T05:45:00.000Z',
    status: 'pending',
    source: 'website',
  },
  {
    id: 'QK-DEMO-1002',
    customerName: 'Rohan M.',
    phone: '9123456780',
    orderMode: 'Pickup',
    items: [
      {
        menuItemId: 'mutton-galouti',
        name: 'Mutton Galouti Kebab',
        variantId: '8pcs',
        variantLabel: '8 Pcs',
        unitPrice: 550,
        quantity: 1,
      },
      {
        menuItemId: 'ulte-tawa-paratha',
        name: 'Ulte Tawa Paratha',
        variantId: '1pc',
        variantLabel: '1 Pc',
        unitPrice: 40,
        quantity: 4,
      },
    ],
    totalPrice: 710,
    totalItems: 5,
    createdAt: '2026-09-09T04:20:00.000Z',
    status: 'preparing',
    source: 'website',
  },
  {
    id: 'QK-DEMO-1003',
    customerName: 'Priya S.',
    phone: '9988776655',
    address: '100 Ft Road, near metro',
    orderMode: 'Delivery',
    items: [
      {
        menuItemId: 'lucknowi-dum-gosht',
        name: 'Lucknowi Dum Gosht Biryani',
        variantId: '2pcs',
        variantLabel: '2 Pcs',
        unitPrice: 275,
        quantity: 2,
      },
      {
        menuItemId: 'shahi-tukda',
        name: 'Shahi Tukda',
        variantId: 'plate',
        variantLabel: '1 Plate',
        unitPrice: 175,
        quantity: 1,
      },
    ],
    totalPrice: 725,
    totalItems: 3,
    note: 'Call on arrival',
    createdAt: '2026-09-08T19:15:00.000Z',
    status: 'delivered',
    source: 'website',
  },
  {
    id: 'QK-DEMO-1004',
    customerName: 'Dev Shah',
    phone: '9001122334',
    orderMode: 'Pickup',
    items: [
      {
        menuItemId: 'bhuna-gosht-korma',
        name: 'Bhuna Gosht Korma',
        variantId: 'half',
        variantLabel: 'Half (3 Pcs)',
        unitPrice: 450,
        quantity: 1,
      },
      {
        menuItemId: 'dei-ka-paratha',
        name: 'Dei Ka Paratha',
        variantId: '2pcs',
        variantLabel: '2 Pcs',
        unitPrice: 130,
        quantity: 1,
      },
    ],
    totalPrice: 580,
    totalItems: 2,
    createdAt: '2026-09-08T13:50:00.000Z',
    status: 'confirmed',
    source: 'whatsapp',
  },
  {
    id: 'QK-DEMO-1005',
    customerName: 'Sana Iqbal',
    phone: '9812345678',
    address: 'HAL 2nd Stage',
    orderMode: 'Delivery',
    items: [
      {
        menuItemId: 'kalkatiya-dum-gosht',
        name: 'Kalkatiya Dum Gosht Biryani',
        variantId: '3pcs',
        variantLabel: '3 Pcs (1 egg, 1 potato)',
        unitPrice: 615,
        quantity: 1,
      },
      {
        menuItemId: 'kesari-lassi',
        name: 'Kesari Lassi',
        variantId: 'glass',
        variantLabel: '1 Glass',
        unitPrice: 150,
        quantity: 2,
      },
    ],
    totalPrice: 915,
    totalItems: 3,
    createdAt: '2026-09-07T20:05:00.000Z',
    status: 'ready',
    source: 'website',
  },
];
